from .home import home
from .connection import Connection
from .auth.logout import logout_user
from .auth.register import register_form
from .lot.list import lot_list
from .lot.detail import lot_details
from .lot.form import add_lot_form
from .account.detail import account_details
from .payment_types.list import payment_list
from .payment_types.form import payment_form
from .vehicles.form import vehicle_form
from .vehicles.list import vehicle_list
